name: 'build_foo'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with: 
      mode: '["build"]'
      alphas: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "workman",
        "qwerty",
        "qwertz",
        "workman"
      ]'
      nav: '[
        "default",
        "invertedt"
        "vi"
      ]'
      clipboard: '[
        "default",
        "fun",
        "mac",
        "win"
      ]'
      layers: '[
        "default",
        "flip"
      ]'
      mapping: '[
        "default",
        "noreverseangle",
        "lite"
      ]'
      kmonad_os: '[
        "default",
        "mac",
        "win"
      ]'
